In [ ]:
import numpy as np

In [ ]:
ejemplo1 = np.random.randn(3, 4)

In [ ]:
ejemplo1.shape

(3, 4)

In [ ]:
ejemplo1

array([[ 0.74106382, -0.47511134,  0.4868888 , -0.16067784],
       [-0.1073899 , -0.02115867,  1.06325927, -1.07540347],
       [ 1.17660092,  0.71327307,  0.52705737, -1.00352491]])

In [ ]:
print(ejemplo1[1:2, 2:4])
print(ejemplo1[1, [2,3]])
print(ejemplo1[[1], [2,3]])
print(ejemplo1[np.newaxis, 1, [2,3]])

[[ 1.06325927 -1.07540347]]
[ 1.06325927 -1.07540347]
[ 1.06325927 -1.07540347]
[[ 1.06325927 -1.07540347]]



`
  [1.06325927   ,  -1.07540347
  0.52705737    , -1.00352491
`



In [ ]:
print(ejemplo1[1:2, 2:4])
print(ejemplo1[1:2, 2:4].shape)
print(ejemplo1[1, [2,3]])
print(ejemplo1[1, [2,3]].shape)
print(ejemplo1[[1], [2,3]])
print(ejemplo1[[1], [2,3]].shape)
print(ejemplo1[np.newaxis, 1, [2,3]])
print(ejemplo1[np.newaxis, 1, [2,3]].shape)

[[ 1.06325927 -1.07540347]]
(1, 2)
[ 1.06325927 -1.07540347]
(2,)
[ 1.06325927 -1.07540347]
(2,)
[[ 1.06325927 -1.07540347]]
(1, 2)


In [ ]:
28, 28, 1
28, 28, 1

In [ ]:
ejemplo4 = np.random.randn(100, 28, 28)

In [ ]:
ejemplo4.shape

(100, 28, 28)

In [ ]:
ejemplo5 = ejemplo4.reshape(100, 28, 1, 28, 1)
ejemplo5.shape

(100, 28, 1, 28, 1)